MIlestone 3: Portfolio Mobile Version.
Leon-Espitia/Portfolio-project-set-up-and-mobile-version-skeleton pull request #3
Opened 2022-05-31 21:18 UTC by Leon-Espitia

## Mobile Version: Contact Form 👨‍💻 
In this Milestone I:
- Added the final section on the Portfolio Mobile Version (Contact Form).
- Apply remote pair programming so I got contributions from my coding partner. (Mustafa Fahimy). 🤝

2022-05-31 21:38 UTC, vechicin requested changes
# Hi @Leon-Espitia  ✋, 

Good job so far! 🔥 
There are some issues that you still need to work on to go to the next project but you are almost there! 🚨 
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights ⚡ 

- [x] Fantastic PR title/description
- [x] Good commit history
- [x] Correct GitHub Flow

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions 📂 
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-31 21:38 UTC, vechicin commented on index.html
> +                    <input type="text" id="email_contact" placeholder="Email" required>
According to the project requirements, this `<input>` should be of `type="email"`.

<img width="231" alt="Screen Shot 2022-05-31 at 16 28 40" src="https://user-images.githubusercontent.com/82426682/171287545-9fc72aad-a246-4807-8b55-f46edea5d57a.png">

Kindly fix this.

2022-05-31 21:38 UTC, vechicin commented on style.css
> +}
Your design doesn't look quite like the template design.

Here's your design:

<img width="247" alt="Screen Shot 2022-05-31 at 16 31 28" src="https://user-images.githubusercontent.com/82426682/171287858-9f6b6e19-4949-4537-a033-dfe60aa80486.png">

Here's the template design:

<img width="277" alt="Screen Shot 2022-05-31 at 16 32 13" src="https://user-images.githubusercontent.com/82426682/171287947-ce7c4b98-d222-4303-ba18-d32968911987.png">
(I apologize about the colored borders, I had to take the screenshot while other students were working on the template.)

Do you see how different they are? Kindly fix your design as it is a project requirement.

Additionally, there is now a strange margin to the right of the other sections' layout and to the left of the contact form. Kindly fix that as well.

<img width="900" alt="Screen Shot 2022-05-31 at 16 34 04" src="https://user-images.githubusercontent.com/82426682/171288159-f266b75a-5c05-4081-b480-8a5df98a49a7.png">

2022-05-31 21:38 UTC, vechicin commented on style.css
> +}
According to the project requirements, this button should have styling for several interactions and those stylings should follow the template design. You are missing a couple of stylings and the ones you have don't follow the template design. Kindly fix this.

<img width="905" alt="Screen Shot 2022-05-31 at 16 35 56" src="https://user-images.githubusercontent.com/82426682/171288398-9c878dad-ff2e-4ae4-bc8b-c40667f9b329.png">

<img width="744" alt="Screen Shot 2022-05-31 at 16 36 16" src="https://user-images.githubusercontent.com/82426682/171288447-8c257d2c-c09c-49bb-b43a-d91373c787e6.png">

2022-06-01 01:57 UTC, Kakalanp requested changes
# STATUS: Changes required :exclamation: 

### Hello there @Leon-Espitia ! <img src="https://user-images.githubusercontent.com/1303154/88677602-1635ba80-d120-11ea-84d8-d263ba5fc3c0.gif" width="28" alt="hi">

### Great work on making the changes requested by a previous reviewer 👏
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet. :memo: 

<img src="https://media.giphy.com/media/xUOxfh6ZM75efM3Bqo/giphy-downsized.gif" alt="almost there">

## Highlights :+1: 
- No linter errors :heavy_check_mark:
- Repo looks professional :briefcase:
- Solid pull request :scroll:
- Good UI design :monocle_face: 

 ## Required Changes ♻️
***Check the comments under the review.***

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

### Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-01 01:57 UTC, Kakalanp commented on style.css
> +}
Kindly remove these lines, as they're interfering with the button effect :mag: 

Whenever I remove those from my end, the colors work ideally :thinking:

2022-06-01 02:13 UTC, Kakalanp approved these changes
# STATUS: APPROVED :green_circle: 

### Your project is approved @Leon-Espitia! :tada: 

There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! :clinking_glasses: 

<img src="https://media.giphy.com/media/slOhiKAVFgwr6/giphy-downsized.gif" alt="almost there">

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

### Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-01 02:15 UTC, merged